spring:
  application:
    name: appointment
  liquibase:
    change-log: classpath:/db/postgres/changelog-master.xml
    enabled: true
    default-schema: ${DB_SCHEMA:appointment}
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appointment_db?currentSchema=appointment}
    username: ${DB_USERNAME:appointment_admin}
    password: ${DB_PASSWORD:12345}
  logging:
    level:
      root: DEBUG
      liquibase: DEBUG
server:
  servlet:
    context-path: /appointment-service