name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Убедитесь, что это версия JDK, которую использует ваш проект
        distribution: 'temurin'

    - name: Build and test with Maven
      run: mvn clean verify

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco
